export type Status = 'not-started' | 'in-progress' | 'done'

export interface SubTask {
  id: string
  label: string
  status: Status
  note: string
}

export interface Phase {
  id: string
  number: number
  title: string
  description: string
  color: string
  glowColor: string
  tasks: SubTask[]
}

export const PHASES: Phase[] = [
  {
    id: 'phase-1',
    number: 1,
    title: 'Problem Definition',
    description: 'Lock the invariant. Define exactly what we are solving.',
    color: '#60A5FA',
    glowColor: 'rgba(96, 165, 250, 0.3)',
    tasks: [
      { id: 'p1-t1', label: 'Lock the core problem statement', status: 'done', note: 'Multi-step agentic workflows execute without durable governance enforcement across execution boundaries.' },
      { id: 'p1-t2', label: 'Lock the core invariant (one sentence)', status: 'done', note: 'No external side effect may execute unless it satisfies the current session\'s immutable and dynamically evolving constraint set.' },
      { id: 'p1-t3', label: 'Lock the system name', status: 'done', note: 'Agent Governance — Interceptor + State Store Pattern' },
      { id: 'p1-t4', label: 'Confirm what this is NOT solving', status: 'done', note: 'Not IAM replacement. Not prompt alignment. Not model fine-tuning. Not a policy language.' },
    ],
  },
  {
    id: 'phase-2',
    number: 2,
    title: 'Stakeholders & Scope',
    description: 'Define who reads this and what is in or out of scope.',
    color: '#A78BFA',
    glowColor: 'rgba(167, 139, 250, 0.3)',
    tasks: [
      { id: 'p2-t1', label: 'Identify primary readers — Sailesh (VP) vs Director', status: 'done', note: 'Sailesh: strategic fit, where it sits in the stack. Director: consistency model, threat surface, design decisions.' },
      { id: 'p2-t2', label: 'Define in-scope for MVP', status: 'done', note: 'Session creation, identity binding, cross-step state mutation, deterministic validation, concurrency-safe enforcement, audit logging.' },
      { id: 'p2-t3', label: 'Define explicit out-of-scope', status: 'done', note: 'Policy language design, IAM replacement, UI dashboards, multi-region replication, production-scale deployment.' },
      { id: 'p2-t4', label: 'Confirm success criteria', status: 'done', note: 'Three scenarios run deterministically. Identity block, cross-step block, budget block all demonstrated.' },
    ],
  },
  {
    id: 'phase-3',
    number: 3,
    title: 'Requirements',
    description: 'Functional and non-functional requirements. The Navik brief.',
    color: '#34D399',
    glowColor: 'rgba(52, 211, 153, 0.3)',
    tasks: [
      { id: 'p3-t1', label: 'FR-1: Session creation with immutable principal binding', status: 'not-started', note: '' },
      { id: 'p3-t2', label: 'FR-2: Durable session-level constraint storage', status: 'not-started', note: '' },
      { id: 'p3-t3', label: 'FR-3: Identity continuity enforcement on each request', status: 'not-started', note: '' },
      { id: 'p3-t4', label: 'FR-4: Dynamic constraint mutation during session', status: 'not-started', note: '' },
      { id: 'p3-t5', label: 'FR-5: Cross-tool invariant enforcement', status: 'not-started', note: '' },
      { id: 'p3-t6', label: 'FR-6: Deterministic violation blocking', status: 'not-started', note: '' },
      { id: 'p3-t7', label: 'FR-7: Append-only audit logging of all decisions', status: 'not-started', note: '' },
      { id: 'p3-t8', label: 'FR-8: Concurrent request safety', status: 'not-started', note: '' },
      { id: 'p3-t9', label: 'NFR-1: Validation latency < 10ms (demo target)', status: 'not-started', note: '' },
      { id: 'p3-t10', label: 'NFR-2: State updates must be atomic', status: 'not-started', note: '' },
      { id: 'p3-t11', label: 'NFR-3: Read-modify-write must be linearizable', status: 'not-started', note: '' },
      { id: 'p3-t12', label: 'NFR-4: System must tolerate agent retries without violation', status: 'not-started', note: '' },
      { id: 'p3-t13', label: 'NFR-5: Enforcement independent of agent logic', status: 'not-started', note: '' },
      { id: 'p3-t14', label: 'Produce: docs/requirements.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-4',
    number: 4,
    title: 'System Architecture',
    description: 'How every component fits together. The building blueprint.',
    color: '#F59E0B',
    glowColor: 'rgba(245, 158, 11, 0.3)',
    tasks: [
      { id: 'p4-t1', label: 'Lock all components and their responsibilities', status: 'not-started', note: '' },
      { id: 'p4-t2', label: 'Lock the two-read model (agent = planning, interceptor = enforcement)', status: 'not-started', note: '' },
      { id: 'p4-t3', label: 'Lock data flow: User → Agent → Interceptor → Tool', status: 'not-started', note: '' },
      { id: 'p4-t4', label: 'Lock that interceptor is the sole path to all tools', status: 'not-started', note: '' },
      { id: 'p4-t5', label: 'Replace 2PC language with pre-execution validation gate', status: 'not-started', note: '' },
      { id: 'p4-t6', label: 'Document why agent is fully untrusted', status: 'not-started', note: '' },
      { id: 'p4-t7', label: 'Produce: docs/architecture.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-5',
    number: 5,
    title: 'Data Model',
    description: 'What the system stores and how. The foundation everything reads from.',
    color: '#F472B6',
    glowColor: 'rgba(244, 114, 182, 0.3)',
    tasks: [
      { id: 'p5-t1', label: 'Design sessions table (principal binding, expiry, active)', status: 'not-started', note: '' },
      { id: 'p5-t2', label: 'Design constraints table (append-only, versioned)', status: 'not-started', note: '' },
      { id: 'p5-t3', label: 'Design execution_log table (append-only, full audit trail)', status: 'not-started', note: '' },
      { id: 'p5-t4', label: 'Confirm append-only design decision and why', status: 'not-started', note: '' },
      { id: 'p5-t5', label: 'Confirm what fields are immutable after creation', status: 'not-started', note: '' },
      { id: 'p5-t6', label: 'Document transaction boundary for read-validate-write', status: 'not-started', note: '' },
      { id: 'p5-t7', label: 'Produce: docs/data_model.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-6',
    number: 6,
    title: 'API Specification',
    description: 'Exact interfaces between every component. Nothing ambiguous.',
    color: '#38BDF8',
    glowColor: 'rgba(56, 189, 248, 0.3)',
    tasks: [
      { id: 'p6-t1', label: 'Define POST /session/create — request + response + side effects', status: 'not-started', note: '' },
      { id: 'p6-t2', label: 'Define POST /execute — request + response + side effects', status: 'not-started', note: '' },
      { id: 'p6-t3', label: 'Define GET /session/log — request + response', status: 'not-started', note: '' },
      { id: 'p6-t4', label: 'Define all constraint keys and their types', status: 'not-started', note: '' },
      { id: 'p6-t5', label: 'Define all tool names and what they represent', status: 'not-started', note: '' },
      { id: 'p6-t6', label: 'Define InterceptorDecision object', status: 'not-started', note: '' },
      { id: 'p6-t7', label: 'Produce: docs/api_spec.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-7',
    number: 7,
    title: 'Consistency Model',
    description: 'Why eventual consistency breaks this. What linearizability guarantees.',
    color: '#FB923C',
    glowColor: 'rgba(251, 146, 60, 0.3)',
    tasks: [
      { id: 'p7-t1', label: 'Explain why eventual consistency is a security vulnerability here', status: 'not-started', note: '' },
      { id: 'p7-t2', label: 'Document the budget race condition example (two agents, $500 each)', status: 'not-started', note: '' },
      { id: 'p7-t3', label: 'Explain linearizable read-modify-write requirement', status: 'not-started', note: '' },
      { id: 'p7-t4', label: 'Document the transaction flow inside interceptor', status: 'not-started', note: '' },
      { id: 'p7-t5', label: 'SELECT session FOR UPDATE', status: 'not-started', note: '' },
      { id: 'p7-t6', label: 'Validate identity + constraints', status: 'not-started', note: '' },
      { id: 'p7-t7', label: 'Mutate state if needed', status: 'not-started', note: '' },
      { id: 'p7-t8', label: 'INSERT audit log + COMMIT', status: 'not-started', note: '' },
      { id: 'p7-t9', label: 'Produce: docs/consistency_model.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-8',
    number: 8,
    title: 'Threat Model',
    description: 'Every attack vector. Every mitigation. No surprises in the director call.',
    color: '#EF4444',
    glowColor: 'rgba(239, 68, 68, 0.3)',
    tasks: [
      { id: 'p8-t1', label: 'Threat 1: Identity impersonation (Sasha/Eve) + mitigation', status: 'not-started', note: '' },
      { id: 'p8-t2', label: 'Threat 2: Compromised or manipulated agent + mitigation', status: 'not-started', note: '' },
      { id: 'p8-t3', label: 'Threat 3: Concurrent race condition + mitigation', status: 'not-started', note: '' },
      { id: 'p8-t4', label: 'Threat 4: Replay attack + mitigation', status: 'not-started', note: '' },
      { id: 'p8-t5', label: 'Threat 5: Direct tool bypass (skipping interceptor) + mitigation', status: 'not-started', note: '' },
      { id: 'p8-t6', label: 'For each threat: which component enforces the mitigation', status: 'not-started', note: '' },
      { id: 'p8-t7', label: 'Produce: docs/threat_model.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-9',
    number: 9,
    title: 'Test Plan',
    description: 'What each test proves architecturally. Not just does it run.',
    color: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.3)',
    tasks: [
      { id: 'p9-t1', label: 'TC-01: Legitimate request → allowed (baseline)', status: 'not-started', note: '' },
      { id: 'p9-t2', label: 'TC-02: Identity mismatch → blocked', status: 'not-started', note: '' },
      { id: 'p9-t3', label: 'TC-03: PII access → allowed + state recorded', status: 'not-started', note: '' },
      { id: 'p9-t4', label: 'TC-04: Unrelated action after PII → allowed', status: 'not-started', note: '' },
      { id: 'p9-t5', label: 'TC-05: Slack after PII → blocked by Step 1 (cross-step causality)', status: 'not-started', note: '' },
      { id: 'p9-t6', label: 'TC-06: Budget spend within limit → allowed', status: 'not-started', note: '' },
      { id: 'p9-t7', label: 'TC-07: Cumulative budget exceeded → blocked', status: 'not-started', note: '' },
      { id: 'p9-t8', label: 'TC-08: Concurrent budget race → only one allowed', status: 'not-started', note: '' },
      { id: 'p9-t9', label: 'TC-09: Retry after block → still blocked', status: 'not-started', note: '' },
      { id: 'p9-t10', label: 'For each TC: document what architectural invariant it proves', status: 'not-started', note: '' },
      { id: 'p9-t11', label: 'Produce: docs/test_plan.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-10',
    number: 10,
    title: 'Implementation',
    description: 'The actual working code. Built last. Against everything locked above.',
    color: '#8B5CF6',
    glowColor: 'rgba(139, 92, 246, 0.3)',
    tasks: [
      { id: 'p10-t1', label: 'state_store.py — init_db()', status: 'not-started', note: '' },
      { id: 'p10-t2', label: 'state_store.py — create_session()', status: 'not-started', note: '' },
      { id: 'p10-t3', label: 'state_store.py — get_session()', status: 'not-started', note: '' },
      { id: 'p10-t4', label: 'state_store.py — set_constraint() append-only', status: 'not-started', note: '' },
      { id: 'p10-t5', label: 'state_store.py — get_constraint() latest value', status: 'not-started', note: '' },
      { id: 'p10-t6', label: 'state_store.py — log_execution() append-only', status: 'not-started', note: '' },
      { id: 'p10-t7', label: 'interceptor.py — session existence + validity check', status: 'not-started', note: '' },
      { id: 'p10-t8', label: 'interceptor.py — identity binding check', status: 'not-started', note: '' },
      { id: 'p10-t9', label: 'interceptor.py — dynamic constraint checks', status: 'not-started', note: '' },
      { id: 'p10-t10', label: 'interceptor.py — atomic read-validate-write transaction', status: 'not-started', note: '' },
      { id: 'p10-t11', label: 'interceptor.py — audit log write on every decision', status: 'not-started', note: '' },
      { id: 'p10-t12', label: 'agent_simulator.py — Scenario 1: Identity impersonation', status: 'not-started', note: '' },
      { id: 'p10-t13', label: 'agent_simulator.py — Scenario 2: Constraint decay (PII → Slack)', status: 'not-started', note: '' },
      { id: 'p10-t14', label: 'agent_simulator.py — Scenario 3: Concurrent budget race', status: 'not-started', note: '' },
      { id: 'p10-t15', label: 'Verify all scenarios run and produce correct output', status: 'not-started', note: '' },
      { id: 'p10-t16', label: 'Produce: prototype/ folder', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-11',
    number: 11,
    title: 'Observability & Risks',
    description: 'What we log, what can go wrong, and how we mitigate it.',
    color: '#06B6D4',
    glowColor: 'rgba(6, 182, 212, 0.3)',
    tasks: [
      { id: 'p11-t1', label: 'Document what the audit log captures and why', status: 'not-started', note: '' },
      { id: 'p11-t2', label: 'Document validation latency target and measurement', status: 'not-started', note: '' },
      { id: 'p11-t3', label: 'Risk: Central bottleneck → mitigation: stateless interceptor', status: 'not-started', note: '' },
      { id: 'p11-t4', label: 'Risk: High latency → mitigation: epoch-based constraint caching', status: 'not-started', note: '' },
      { id: 'p11-t5', label: 'Risk: Overlap with IAM → mitigation: position as session-layer governance', status: 'not-started', note: '' },
      { id: 'p11-t6', label: 'Risk: Complexity creep → mitigation: keep MVP minimal', status: 'not-started', note: '' },
      { id: 'p11-t7', label: 'Produce: docs/risks.md', status: 'not-started', note: '' },
    ],
  },
  {
    id: 'phase-12',
    number: 12,
    title: 'README',
    description: 'The front door. Written last. Ties everything together.',
    color: '#D97706',
    glowColor: 'rgba(217, 119, 6, 0.3)',
    tasks: [
      { id: 'p12-t1', label: 'Opening — the problem in plain language (Navik analogy)', status: 'not-started', note: '' },
      { id: 'p12-t2', label: 'The core invariant — one line', status: 'not-started', note: '' },
      { id: 'p12-t3', label: 'Architecture diagram (text-based, clear)', status: 'not-started', note: '' },
      { id: 'p12-t4', label: 'Full repo structure', status: 'not-started', note: '' },
      { id: 'p12-t5', label: 'Quickstart — how to run in one command', status: 'not-started', note: '' },
      { id: 'p12-t6', label: 'What each scenario proves', status: 'not-started', note: '' },
      { id: 'p12-t7', label: 'Why not JWT / IAM / OPA / Temporal — addressed cleanly', status: 'not-started', note: '' },
      { id: 'p12-t8', label: 'Production path — what swaps out at scale', status: 'not-started', note: '' },
      { id: 'p12-t9', label: 'Links to all docs', status: 'not-started', note: '' },
      { id: 'p12-t10', label: 'Written to satisfy both Sailesh and the Director', status: 'not-started', note: '' },
      { id: 'p12-t11', label: 'Produce: README.md', status: 'not-started', note: '' },
    ],
  },
]
